#define WATER_SERVO_ARM 9
#define COIN_SERVO_ARM 6
#define MAGNET_SERVO 7
#define DOOR_SERVO 8
#define MOTOR_1A 3
#define MOTOR_1B 2
#define BUTTON_LEFT 
#define BUTTON_RIGHT 

#define DOOR_CLOSED_ANGLE 150
#define DOOR_OPEN_ANGLE 100
#define COIN_ARM_INIT_ANGLE 170
#define COIN_ARM_TASK_ANGLE 50
#define WATER_ARM_INIT_ANGLE 20
#define WATER_ARM_TASK_ANGLE 100